### ISSUE TITLE
No newcheckpoints

### ISSUE THREAD

**Issue by Zhousiyuhit** [a7b23/MazePathFinder#1]
hi, thanks for posting the project, I encountered one problem when I run testing.py, there was a message that: tensorflow.python.framework.errors.NotFoundError: NewCheckpoints

**Comment by Zhousiyuhit** [comment]
sorry, I have resolved this problem.

**Comment by a7b23** [comment]
Hi , hope you are getting the desired results now. If yes then I would close this issue now.

**Comment by Zhousiyuhit** [comment]
yes, thank you very much. however, I have another question to ask you, how long do you train your model?

**Comment by a7b23** [comment]
The training takes around 10-12 hours of time when using CPU . With GPU it should take much less time.

**Comment by Zhousiyuhit** [comment]
Oh my god, maybe I should use TX1 to train the model

**Comment by guest-oo** [comment]
你好 我增加到4个运动方向，第二个神经网络需要扩展到4吗？我尝试扩展到4，但是最终的结果是无解
