### ISSUE TITLE
High pixel pictures

### ISSUE THREAD

**Issue by Zhousiyuhit** [a7b23/MazePathFinder#2]
Hi, recently I thought about another question: do you think this model can be used in a high pixel images? Now the image is 25X25 size, if I want to train this model within the 100X100 image, do you think is an applicable idea?

**Comment by a7b23** [comment]
I did not experiment with higher pixel images . Maybe you would need to tweak the parameters a bit.

**Comment by Zhousiyuhit** [comment]
Thank you very much, maybe I can try it, if success, I will post the result for you.

**Comment by a7b23** [comment]
Yeah sure do go ahead and report the results which you get.
